dist: bionic
language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
python:
  - "2.7"
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-lint
    - python: "3.7"
      env: TOXENV=py37-lint
    - python: "2.7"
      env: TOXENV=py27-Plone51
    - python: "2.7"
      env: TOXENV=py27-Plone52
    - python: "3.7"
      env: TOXENV=py37-Plone52
  fast_finish: true

before_install:
  - virtualenv -p `which python` .
  - mkdir -p $HOME/buildout-cache/{eggs}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - sudo apt-get install -y firefox-geckodriver

install:
  - travis_retry pip install -U tox isort coveralls coverage -c constraints.txt

before_script:
- 'export DISPLAY=:99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- sleep 3
- firefox -v

script:
  - tox

after_success:
  - python -m coverage.pickle2json
  - coverage combine
  - coveralls
